### ISSUE TITLE
このライブラリが提供するコンポーネント体系を大まかに描く

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#1]
想定している画面パターンから、必要そうなコンポーネントを洗い出し、分類/整理する

```
* 一覧
    * 一覧検索/表示
    * 一括登録/更新/削除
    * 一括削除
* 単票
    * 詳細
    * 登録/更新/削除

* アプリケーションのフレーム
    * ヘッダー
    * フッター
    * サイドバー
* その他
    * ログイン
    * ダッシュボード/マイページ/タイムライン
    * 設定
    * エラー
```

コンポーネントの粒度、分類/整理にあたっては既存の有名コンポーネントライブラリを参考にする

https://next.vuetifyjs.com/en/components/all/
https://buefy.org/documentation

**Comment by kondoriyo** [comment]
# ターゲット画面の必要部品の洗い出し

**1.  一覧**

#### 一覧検索, 一覧表示

- Form
  - Input  
  - Selectbox
  - Datepicker
  - MultiSelectbox
  - Checkbox 
- Button 
- Table
- Pagination
- List
- Dialog
- Modal 
- Icon 
- Divider 
- Breadcrumb 
- Grid 
- EveryLayout
  - Grid
  - Sidebar
  - Cluster
  - Box
  - Stack
  - Reel

#### 一括登録/更新 -> 一覧画面上のテーブルセル上での一括更新、xls/csvなどのファイルアップロード

- 入力可能なテーブル？ 
- Upload 
- Alerts / Notification 
- EveryLayout
  - Grid
  - Box
  - Stack
  - Reel
  - Cluster
 
#### 一括削除 -> CB アプリケーション画面
- Dropdown 
- Dialog
- Checkbox

**2. 単票**

#### 詳細

- Form
  - Input
- Tabs 
- Button
- EveryLayout
  - Box
  - Stack
  - Grid
  - Cluster

#### 登録 

- Form
  - input
  - Datepicker
  - MultiSelect
  - Upload
- Button
- Tabs
- EveryLayout
  - Box
  - Stack
  - Grid
  - Cluster

#### 更新

- Form
  - input
  - Datepicker
  - MultiSelect
  - Upload
- Dialog
- Button
- Tabs
- EveryLayout
  - Box
  - Stack
  - Grid
  - Cluster

#### 削除 

- Dropdown
- Dialog
- Checkbox

**3. フレーム** 
#### ヘッダー

- Icon
- Dropdown
- EveryLayout
  - Box
  - Cluster

#### フッター

- Button 
- Footers
- EveryLayout
  - Box
  - Stack
  - Center

#### サイドバー 

- EveryLayout
  - Sidebar


**4. その他**
#### ログイン

- input
- Button
- Card 
- EveryLayout
  - Box
  - Center
  - Stack

#### ダッシュボード, マイページ, タイムライン

- Timeline 
- Sheets 
- Chips / Tag
- EveryLayout
  - Box
  - Stack
  - Cluster
  - Sidebar

#### 設定

- Menu / Sidebar 
- Switch 
- input
- button
- Card
- EveryLayout
  - Box
  - Stack
  - Cluster
  - Sidebar

#### エラー

- Notification
- Loading

**Comment by kondoriyo** [comment]
# コンポーネントの分類

- Form
  - [Autocomplete](https://buefy.org/documentation/autocomplete)
  - [Button](https://buefy.org/documentation/button)
  - [Field](https://buefy.org/documentation/field)
  - [NumberInput](https://buefy.org/documentation/input)
  - [TextInput](https://buefy.org/documentation/input)
  - [PasswordInput](https://buefy.org/documentation/input)
  - [Textarea](https://buefy.org/documentation/input)
  - [Select](https://buefy.org/documentation/select)
  - [Combobox](https://vuetifyjs.com/ja/components/combobox/)
  - [Checkbox](https://buefy.org/documentation/checkbox)
  - [Datepicker](https://buefy.org/documentation/datepicker)
  - [Radio](https://buefy.org/documentation/radio)
  - [Switch](https://buefy.org/documentation/switch)
  - [Upload](https://buefy.org/documentation/upload)
- Data
  - [Card](https://next.vuetifyjs.com/en/components/cards/)
  - [Divider](https://next.vuetifyjs.com/en/components/dividers/)
  - [Icon](https://buefy.org/documentation/icon)
  - [List](https://next.vuetifyjs.com/en/components/lists/)
  - [Table](https://buefy.org/documentation/table)
  - [Tag](https://buefy.org/documentation/tag)
  - [Timeline](https://next.vuetifyjs.com/en/components/timelines/)
- Feedback
  - [Alert](https://next.vuetifyjs.com/en/components/alerts/) / [Notification](https://buefy.org/documentation/notification)
  - [Loading](https://buefy.org/documentation/loading)
  - [Dialog](https://buefy.org/documentation/dialog)
- Navigation
  - [Breadcrumbs](https://buefy.org/documentation/breadcrumb)
  - [Dropdown](https://buefy.org/documentation/dropdown)
  - [Footer](https://next.vuetifyjs.com/en/components/footers/)
  - [Menu](https://buefy.org/documentation/menu)
  - [Tabs](https://buefy.org/documentation/tabs)
  - [Sidebar](https://buefy.org/documentation/sidebar)
  - [Steps](https://buefy.org/documentation/steps)
  - [Pagination](https://buefy.org/documentation/pagination)
- Overlay
  - [Modal](https://buefy.org/documentation/modal)
  - [Tooltip](https://buefy.org/documentation/tooltip)
  - [Toast](https://buefy.org/documentation/toast)
- Layout
  - Box
  - Stack
  - Center
  - Cluster
  - Sidebar
  - Switcher
  - Cover
  - Grid
  - Frame
  - Reel
  - Imposter
  - Icon
