### ISSUE TITLE
デフォルトカラーパレットを設計し、Buttonに適用する

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#11]
refs. #5 

src直下に以下のようなvariables.cssというファイルを置き、各コンポーネントはpropsとこのCSS変数に基づいて自身のカラーリングを決める。

```src/variables.css
:root {
    --jupiter-white: rgb(255 255 255);
    --jupiter-light: ...;
    --jupiter-dark: ...;
    --jupiter-black: ...;

    --jupiter-primary: ...;
    --jupiter-link: ...;
    --jupiter-info: ...;
    --jupiter-success: ...;
    --jupiter-warning: ...;
    --jupiter-danger: ...;
...
}
```

ライブラリ利用者側はこのCSS変数を上書きすることで、自身のプロジェクトに合ったカラーリングへカスタマイズできるようにする。

参考：MUI
https://mui.com/material-ui/customization/default-theme/?expand-path=$.palette#explore
参考：Vuetify
https://next.vuetifyjs.com/en/features/theme/
参考：Buefy（Bulma）
https://bulma.io/documentation/customize/variables/

**Comment by kbtaniguchi** [comment]
その差異、hover、focus、disableの際のスタイルも意識する

**Comment by kondoriyo** [comment]
マージしたのでcloseします
