### ISSUE TITLE
最初の実装ターゲットになる最小セットのコンポーネントを選定する

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#2]
https://github.com/actier-luchta/jupiter/issues/1 で整理したコンポーネントのうち、最初の実装ターゲットになる最小セットのコンポーネントを選定する

**Comment by kondoriyo** [comment]
システムコンソールの各画面に必要となるコンポーネントの一覧です

☆各画面------------------------------------------

ホーム画面
* Footer

お知らせ一覧画面
1. 一覧画面
    * Button
    * Checkbox
    * Icon
    * Table
    * Pagination
    * Tag
2. 新規登録画面
    * Field
    * Datepicker
    * TextInput
    * Textarea
    * Selectbox
    * Dialog
    * EveryLayout
        * Box
        * Stack
3. 更新画面
    * Field
    * Datepicker
    * TextInput
    * Textarea
    * Selectbox
    * Dialog
    * EveryLayout
        * Box
        * Stack

アカウント一覧画面
1. 一覧画面
    * Button
    * Table
    * Pagination
    * Icon
    * EveryLayout
        * Stack
        * Box
        * Cluster
        * Reel
2. 新規登録画面
    * TextInput
    * PasswordInput
    * Button
    * EveryLayout
        * Box
        * Stack
3. 更新画面
    * TextInput
    * Button
    * EveryLayout
        * Box
        * Stack

お試しテナント一覧画面
1. 一覧画面
    * Button
    * EveryLayout
        * Box
2. 招待画面
    * TextInput
    * NumberInput
    * Selectbox
    * Button
    * EveryLayout
        * Box
        * Stack

マイアカウント画面
1. マイアカウント画面
    * TextInput
    * PasswordInput
    * Button
    * Dialog
    * EveryLayout
        * Box
        * Stack


☆フレーム------------------------------------------
サイドバー
* Sidebar or Menu
* EveryLayout
    * Sidebar

ヘッダー
*  Button
* EverLayout
    * Cluster
    * Box

フッター
* Footer
* Button

エラー
* Notification
