### ISSUE TITLE
TextFieldコンポーネントを作成する

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#20]
Vuetifyだと↓に相当するが、とりあえずのTextInputはもっと機能を絞ることにする
https://vuetifyjs.com/en/components/text-fields/

機能的に期待することは

* 通常時/エラー時のスタイルを任せられること（入力値の検証はcomponent利用側で行うので、Vuetifyのrule propsのようなものは不要）
* ラベルとエラーメッセージをslotで渡せて、エラーの状態に合わせて適切なスタイルが適用されること

なので、componentのインタフェースとしては以下のようになっていれば良いはず

* props
  * v-modelで入力値をbindできること
  * placeholderを受け取れること
  * error(boolean)を受け取れること
  * disabled, readonly, id, nameなどはフォールスルーを期待すること
* slots
  * labelを受け取れること（inputの上に表示する）
  * error-messageを受け取れること（labelとinputの間に表示する、errorがtrueの場合だけ表示する）
* events
  * focus, blurなどはネイティブイベントのバブリングを期待すること

**Comment by kbtaniguchi** [comment]
vuetifyのText-Fieldはv-inputとv-fieldの２つのコンポーネントを合成してできているらしい

**Comment by kbtaniguchi** [comment]
本文では色々書いたが、やっぱりVuetifyのTextFieldコンポーネントの機能的サブセットを目指すことにする

**Comment by kondoriyo** [comment]
マージしたのでcloseします
