### ISSUE TITLE
Checkboxのエラーのスタイルのトンマナを他のフォーム部品と合わせる

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#47]
チェックボックスの枠とラベルをdangerにする

![Image](https://user-images.githubusercontent.com/26402669/222063636-705d10ac-6a8a-4058-bea3-7ee8755924e8.png)
![Image](https://user-images.githubusercontent.com/26402669/222063637-269074bd-91c5-4f5a-a962-612c07754096.png)

**Comment by kondoriyo** [comment]
マージしたのでcloseします
