### ISSUE TITLE
TextField:エラーメッセージをpropsで渡したい

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#49]
現状のslotで用は足せるのだが、v-forを書いたりするのがやはりめんどう。
エラーメッセージの出し方に特にこだわりがない場合はコンポーネントのスタイルに任せたい。

フィールドのスタイルのエラー判定も、エラーメッセージが設定されていればエラースタイルにする。
propsのisErrorはオプションということにし、propsのisErrorが設定されている場合はそちらを優先する、という仕様にする。
結局Vuetifyのerror, error-messagesの仕様と同じにするのが使いよい。

refs. https://v2.vuetifyjs.com/ja/api/v-text-field/#props

**Comment by kbtaniguchi** [comment]
補足：
<TextField error-message="入力が不正です"> -> error-messageが設定されているのでスタイルをエラーにする
<TextField error> -> error-messageは設定されてないがerrorが設定されているのでスタイルをエラーにする

**Comment by kondoriyo** [comment]
マージしたのでcloseします
