### ISSUE TITLE
componentが期待しているプロパティはフォールスルーに期待せず、propsとして明示する

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#65]
定義するpropsがやたら増えてしまうのがいかがなものかと思い、フォールスルーに頼っていたが、
コンポーネント内部の処理が依存するプロパティが明示されていないことで、

* 使う側はどの属性がサポートされているのか分からない
* ライブラリメンテの際にもどの属性をサポートしているか明示していないので直しづらい

などのデメリットの大きさがあるので、方針転換する

**Comment by kbtaniguchi** [comment]
cypressとかのdata-**のカスタム属性が自由に使えなくなるのは困るかも

**Comment by kondoriyo** [comment]
マージしたのでcloseします
