### ISSUE TITLE
TextArea: 1行以下の高さには縮められないようにしたい

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#80]
![Image](https://user-images.githubusercontent.com/26402669/227463405-c3038efc-b270-436d-9240-0fd07233afd3.png)
今は↑が↓のようになってしまって見た目が崩れてしまうので、
![Image](https://user-images.githubusercontent.com/26402669/227463493-783f8a9a-a435-418b-b39b-114dbcae3933.png)

VuetifyのTextareaのように1行以下の高さには縮められないようにしておきたい

**Comment by kondoriyo** [comment]
マージしたのでcloseします
