### ISSUE TITLE
TextArea: アイコンは上下真ん中寄せではなくて上寄せにする

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/jupiter#85]
テキストエリアのサイズを広げたときに上下真ん中寄せだと違和感を感じる。
Vuetify同様、上寄せにしておく

refs. https://vuetifyjs.com/en/components/textareas/#icons
![Image](https://user-images.githubusercontent.com/26402669/228095049-8c3f3861-a97d-494f-8541-e837e27860ac.png)

**Comment by kondoriyo** [comment]
マージしたのでcloseします
